### ISSUE TITLE
AwesomeWM Attempt to index a nil value

### ISSUE THREAD

**Issue by TalinTheDev** [Aire-One/awesome-battery_widget#3]
I'm using the dotfiles from [saimoomedits](https://github.com/saimoomedits/dotfiles) and I get this AwesomeWM error: 
```
bruh! an error has occured!

/home/admin/.config/awesome/ mods/battery-widget/init.lua:39: attempt to index a nil value
```

My `init.lua` for `awesome-battery_widget` is the default and I have not touched anything.

Thanks

**Comment by Aire-One** [comment]
Hello @TalinTheDev,

Do you have the full stack-trace of the error?

The failing line from the message is

```lua
    local devices = upower.Client():get_devices()
```

Can you make sure you have UPowerGlib correctly installed (https://lazka.github.io/pgi-docs/UPowerGlib-1.0/index.html)?

**Comment by TalinTheDev** [comment]
Thanks for your help but for some reason, when I booted into Arch today morning, after my computer being shutdown overnight, it works now so I think I'm good. Thanks tho!
